const menu =[
  {
    "id": 1,
    "title": "California Roll Sushi Bowls",
    "course": "Main Course",
    "cuisine": "Asian",
    "mainIngredient": "Vegetables",
    "description": "",
    "source": "https://www.cookingclassy.com/california-roll-sushi-bowls/",
    "url": "https://www.cookingclassy.com/california-roll-sushi-bowls/",
    "urlHost": "cookingclassy.com",
    "prepTime": 15,
    "cookTime": 25,
    "totalTime": 40,
    "servings": 5,
    "yield": 5,
    "ingredients": "2 cups dry California Calrose Sushi Rice\n5 Tbsp rice vinegar, (, divided)\n2 Tbsp granulated sugar\n1/2 tsp salt\n1/4 cup light mayonnaise\n1 1/2 Tbsp sriracha\n1/4 cup low-sodium soy sauce\n10 oz imitation crab, or lump crabmeat, (, torn or chopped into small bite size pieces)\n1 1/2 cups diced English cucumber\n3/4 cup roughly chopped matchstick carrots\n1 nori sheet (, chopped or crumbled into small pieces (add more if you'd like))\n1 1/2 Tbsp chopped pickled sushi ginger\n1 large avocado, (, peeled and diced)\nBlack and toasted sesame seeds, (, for garnish)",
    "directions": "Place rice in a fine mesh strainer and rinse under cold water until water runs clear (it will take about 2 minutes of rinsing). Tap bottom of strainer with palm of your hand until water no longer falls from strainer (it should be well drained). Transfer rice to a medium saucepan along with 2 1/4 cups water. Bring mixture to a full boil then reduce heat to low, cover with lid and simmer 15 minutes. Remove from heat, keep covered and let rest 15 minutes.\nMeanwhile, in a small saucepan combine 4 Tbsp of the vinegar with the sugar and salt. Heat over medium heat, cook and whisk until sugar has dissolved. Remove from heat, let cool while rice is resting then pour vinegar mixture over rice and toss to evenly coat.\nIn a small mixing bowl whisk together mayonnaise with sriracha. Thin with 1 1/2 tsp of water if desired. Transfer to a sandwich size resealable bag. Set aside.\nIn a small mixing bowl whisk together soy sauce and remaining 1 Tbsp vinegar, set aside. In a large mixing bowl gently toss together crab meat, cucumber, carrots, nori, ginger and avocado. Divide prepared rice among 4 or 5 bowls. Top with crab mixture then spoon soy sauce mixture over top of each serving. Cut a small tip from one corner of the resealable bag holding the sriracha mixture, drizzle over each serving. Serve immediately.\nRecipe source: adapted with changes from Whole Foods",
    "tags": "Easy, Salad",
    "rating": "",
    "publicUrl": "https://www.plantoeat.com/recipes/16687583",
    "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16687583/d99596b7acb8758e6d878ada11c36bd83c704cf4-original.jpg?1535321755",
    "private": "no",
    "nutritionalScoreGeneric": "",
    "calories": 465,
    "fat": "8 g",
    "cholesterol": "8 mg",
    "sodium": "1185 mg",
    "sugar": "9 g",
    "carbohydrate": "84 g",
    "fiber": "6 g",
    "protein": "10 g",
    "cost": ""
  },
  {
    "id": 2,
    "title": "Chicken Caesar Wraps",
    "course": "Main Course",
    "cuisine": "American",
    "mainIngredient": "Chicken",
    "description": "",
    "source": "https://www.favfamilyrecipes.com/chicken-caesar-wraps/",
    "url": "https://www.favfamilyrecipes.com/chicken-caesar-wraps/",
    "urlHost": "favfamilyrecipes.com",
    "prepTime": 0,
    "cookTime": 20,
    "totalTime": 20,
    "servings": 4,
    "yield": "",
    "ingredients": "2-3 c. romaine lettuce\nCaesar dressing, (to taste.. the better the dressing, the better your wrap will be.. personally I like Brianna's bran\n1/3 c. Parmesan cheese, (freshly grated)\n1 chicken breast, (cooked & diced)\ncroutons, (coarsely chopped)\ndiced tomatoes, (lightly salted)\n2-3 tortilla wraps, (burrito sized, we like the herb flavored kind)",
    "directions": "Toss lettuce, dressing, cheese, chicken, and croutons in a large bowl until everything is lightly coated with dressing. Add tomatoes and lightly toss again. Place salad mixture in the middle of the wrap, wrap up tightly and serve!",
    "tags": "Chicken, Quick, Cheap",
    "rating": "",
    "publicUrl": "https://www.plantoeat.com/recipes/16687602",
    "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16687602/ba918c2550fd60a3f56da6cc510eb24b56752f63-original.jpg?1535321822",
    "private": "no",
    "nutritionalScoreGeneric": "",
    "calories": 280,
    "fat": "8g",
    "cholesterol": "25mg",
    "sodium": "580mg",
    "sugar": "2g",
    "carbohydrate": "36g",
    "fiber": "12%",
    "protein": "15g",
    "cost": ""
  },
  {
    "id": 3,
    "title": "Vegetarian Tacos with Avocado Cream",
    "course": "Main Course",
    "cuisine": "American",
    "mainIngredient": "Vegetables",
    "description": "",
    "source": "https://emilykylenutrition.com/vegetarian-hummus-tacos/",
    "url": "https://emilykylenutrition.com/vegetarian-hummus-tacos/",
    "urlHost": "emilykylenutrition.com",
    "prepTime": 5,
    "cookTime": 5,
    "totalTime": 10,
    "servings": 4,
    "yield": "",
    "ingredients": "For Avocado Cream\n1/2 avocado\n1 cup plain Greek Yogurt\n1 lime, (juiced)\n1 teaspoon homemade taco seasoning\nFor Tacos\n8 whole wheat tortillas\n1 cup roasted red pepper hummus\n1 cup grape tomatoes, (diced)\n1 small cucumber, (diced)\n1 bell pepper, (diced)\n1/2 cup black beans\n1/2 cup frozen corn, (thawed)\n1 cup greens, (shredded)\n1/2 cup fresh sprouts, or microgreens\n1/2 avocado, (diced)",
    "directions": "In a small food processor, blend together the avocado, Greek yogurt, lime juice, and taco seasoning until smooth. Set aside.\nSet out tortillas and fill with a hearty dollop of hummus.\nAdd your fresh toppings.\nTop with avocado cream.\nGarnish with sprouts.\nEnjoy!",
    "tags": "Vegan, Quick",
    "rating": "",
    "publicUrl": "https://www.plantoeat.com/recipes/16687702",
    "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16687702/089722a277be198555dd6c9c1f08476cc3b8eab3-original.jpg?1535322539",
    "private": "no",
    "nutritionalScoreGeneric": "",
    "calories": 410,
    "fat": "18g",
    "cholesterol": "5mg",
    "sodium": "680mg",
    "sugar": "6g",
    "carbohydrate": "54g",
    "fiber": "52%",
    "protein": "14g",
    "cost": ""
  },
  {
    "id": 4,
    "title": "Chicken and Lemon Risotto",
    "course": "Main Course",
    "cuisine": "Italian",
    "mainIngredient": "Rice & Grains",
    "description": "Chicken And Lemon Risotto With Reduced Sodium Chicken Stock, Butter, Boneless Skinless Chicken Breasts, Garlic, Lemon Juice, Fresh Oregano, Onion, Arborio Rice, Frozen Peas, Grated Lemon Peel, Grated Parmesan Cheese",
    "source": "https://www.yummly.com/recipe/Chicken-and-Lemon-Risotto-1407363",
    "url": "https://www.yummly.com/recipe/Chicken-and-Lemon-Risotto-1407363",
    "urlHost": "yummly.com",
    "prepTime": 0,
    "cookTime": 55,
    "totalTime": 55,
    "servings": 4,
    "yield": "4 servings",
    "ingredients": "4 cups reduced sodium chicken stock\n3 tablespoons butter\n1 pound boneless skinless chicken breasts larger pieces halved\n2 cloves garlic crushed\n1/4 cup lemon juice\n2 tablespoons fresh oregano coarsely chopped\n1 onion medium, finely chopped\n1 1/2 cups arborio rice\n3/4 cup frozen peas\n2 teaspoons grated lemon peel finely\n1/4 cup grated parmesan cheese finely",
    "directions": "Place the stock and 1/2 cup water in a medium saucepan. Bring to a boil. Cover and reduce heat to low.\nMeanwhile, melt 1/2 the butter in large saucepan on medium heat. Add the chicken and cook until browned on both sides and just cooked through. Add the garlic, lemon juice and oregano and cook, stirring, until almost all the liquid has evaporated. Remove the chicken from pan and keep warm.\nMelt the remaining butter in the same pan. Add the onion and cook, stirring, until soft. Add the rice, stirring to coat it in the buttery juices. Reduce heat to medium-low. Add a ladleful of hot stock to rice mixture; stir constantly until liquid is absorbed. Continue to add stock, 1 ladleful at a time, stirring constantly until liquid is absorbed before adding more (this will take about 35 mins or until rice is tender but firm to the bite). After 30 mins, stir in the peas.\nAdd the lemon peel, cheese, and salt and pepper to taste. Serve the rice topped with chicken and additional Parmesan shavings, if desired.",
    "tags": "Chicken",
    "rating": "",
    "publicUrl": "https://www.plantoeat.com/recipes/16687774",
    "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16687774/ff717e9ea9e725eb270c6f4b58d38716164bb5cf-original.jpg?1535322745",
    "private": "no",
    "nutritionalScoreGeneric": "",
    "calories": 560,
    "fat": "15 g",
    "cholesterol": "100  mg",
    "sodium": "870  mg",
    "sugar": "3 g",
    "carbohydrate": "69 g",
    "fiber": "5 g",
    "protein": "36 g",
    "cost": ""
  },
  {
    "id": 5,
    "title": "Chicken, Broccoli Risotto",
    "course": "Main Course",
    "cuisine": "Italian",
    "mainIngredient": "Rice & Grains",
    "description": "Chicken, Broccoli Risotto With Arborio Rice, Dry White Wine, Chicken Stock, Leek, Butter, Parmesan Cheese, Chicken Breast, Broccoli, Medium Carrot, Olive Oil",
    "source": "https://www.yummly.com/recipe/Chicken_-Broccoli-Risotto-2035794",
    "url": "https://www.yummly.com/recipe/Chicken_-Broccoli-Risotto-2035794",
    "urlHost": "yummly.com",
    "prepTime": 0,
    "cookTime": 30,
    "totalTime": 30,
    "servings": 4,
    "yield": "",
    "ingredients": "2/3 cup arborio rice 4.2oz, 125gr, or other rice specifically for risotto – Carnaroli or Vialone Nano\n1/2 cup dry white wine 4oz, 120ml\n2 1/4 cups chicken stock 18oz, 540ml\n1 leek medium, trimmed and sliced, divided\n1 tablespoon butter\n3/4 cup parmesan cheese 3oz, 90gr, – freshly grated\n1 chicken breast boneless, skinless, cut into small pieces\n1/2 head broccoli cut into florets with stem\n1 medium carrot cut into matchsticks\n1 tablespoon olive oil",
    "directions": "Heat chicken stock and keep hot over low heat.\nIn medium sauce pan heat butter; add half the leek and sauté until transparent.\nAdd rice and sauté, stirring, for 2 – 3 minutes until rice has white center.\nAdd white wine and stir.\nStart condimenti.\nWhen wine is almost absorbed add a 1/3 cup of stock, stir.  (No need to stir constantly but do stir from time to time.)\nWhen stock is almost absorbed add another 1/3 cup and continue adding 1/3 cup at a time and stirring.  Before adding the last 1/4 cup taste a few kernels of rice.  They should be just ‘al dente’ – slightly resistant to the tooth, but fully cooked.  If more stock is needed add it 1/8 cup at a time and waiting until almost completely absorbed.  At this point risotto will be thick but not stiff – there will still be visible liquid and it will not hold it’s shape on a plate.\nAdd the Parmesan, Condimenti, and stir gently.\nSpoon into a bowl or risotto platter and serve.\nCondimenti:\nHeat oil in a medium skillet, add remaining half leek and sauté until transparent.\nAdd chicken, broccoli, carrot and sauté 5  – 7 minutes.\nAdd 1/4 cup of hot stock, cover, reduce heat and cook until vegetables are tender and chicken done.\nRemove from heat and keep warm until needed.",
    "tags": "Chicken",
    "rating": "",
    "publicUrl": "https://www.plantoeat.com/recipes/16687800",
    "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16687800/9bac872caee028022ce69dce2f6ec1fe57b51b3f-original.jpg?1535322905",
    "private": "no",
    "nutritionalScoreGeneric": "",
    "calories": 400,
    "fat": "14 g",
    "cholesterol": "45  mg",
    "sodium": "590  mg",
    "sugar": "6 g",
    "carbohydrate": "43 g",
    "fiber": "4 g",
    "protein": "22 g",
    "cost": ""
  },
  {
    "id": 6,
    "title": "Banana Bread Mini Muffins Recipe by Tasty",
    "course": "Breakfast",
    "cuisine": "American",
    "mainIngredient": "Fruit",
    "description": "Here's what you need: ripe banana, egg, full-fat greek yogurt, honey, vanilla extract, whole wheat flour, baking soda, strawberry, dark chocolate chip, blueberry, walnuts",
    "source": "https://tasty.co/recipe/banana-bread-mini-muffins",
    "url": "https://tasty.co/recipe/banana-bread-mini-muffins",
    "urlHost": "tasty.co",
    "prepTime": 20,
    "cookTime": 20,
    "totalTime": 40,
    "servings": 12,
    "yield": "12 muffins",
    "ingredients": "3 ripe bananas\n2 eggs\n1/2 cup full-fat Greek yogurt\n1/3 cup honey\n1 teaspoon vanilla extract\n1 1/2 cups whole wheat flour\n1 teaspoon baking soda\nDiced strawberries\nDark chocolate chips\nBlueberries\nChopped walnuts",
    "directions": "Preheat oven to 350°F (180°C).\nIn a large bowl, mash the bananas into a fine paste using a fork.\nAdd the eggs and whisk together until well incorporated.\nAdd in the Greek yogurt, honey, and vanilla extract, then mix.\nPour the flour over the wet mixture then sprinkle in the baking soda.\nUsing a spatula, fold the wet and dry ingredients together until the dry bits of the flour have disappeared.\nUsing a medium ice cream scoop, portion the batter evenly into a greased muffin tin.\nTop the muffins with your choice of toppings.\nBake for 20 minutes, until the muffins have risen and set.\nUnmold from the tray and serve.\nEnjoy!",
    "tags": "Breakfast, Bakery Goods",
    "rating": "",
    "publicUrl": "https://www.plantoeat.com/recipes/16687848",
    "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16687848/e9ac6403eb5f10dc73302c0bd58480b307d2680c-original.jpg?1535323065",
    "private": "no",
    "nutritionalScoreGeneric": "",
    "calories": "",
    "fat": "",
    "cholesterol": "",
    "sodium": "",
    "sugar": "",
    "carbohydrate": "",
    "fiber": "",
    "protein": "",
    "cost": ""
  },
  {
    "id": 7,
    "title": "Protein-Packed Breakfast Bars Recipe by Tasty",
    "course": "Breakfast",
    "cuisine": "",
    "mainIngredient": "",
    "description": "Here's what you need: flax meal, water, rolled oats, quinoa, baking powder, salt, maple syrup, refined coconut oil, vanilla extract, ripe banana, peanut butter chocolate candy, peanut butter, mini chocolate chips, gala apple, walnuts, cinnamon, nutmeg, carrot, cinnamon, nutmeg, almond butter, almond butter, strawberry, raspberry, blueberry, nonstick cooking spray",
    "source": "https://tasty.co/recipe/protein-packed-breakfast-bars",
    "url": "https://tasty.co/recipe/protein-packed-breakfast-bars",
    "urlHost": "tasty.co",
    "prepTime": 20,
    "cookTime": 90,
    "totalTime": 110,
    "servings": 24,
    "yield": "24 bars",
    "ingredients": "1/4 cup flax meal\n3/4 cup water\n6 cups rolled oats\n6 cups cooked quinoa\n4 teaspoons baking powder\n1 teaspoon salt\n1 cup maple syrup\n1/2 cup melted refined coconut oil\n2 teaspoon vanilla extract\n4 ripe mashed bananas\nPeanut Butter Chocolate Chip\n6 tablespoons peanut butter\n5 tablespoons mini chocolate chips\n3/4 cup diced gala apple\n6 tablespoons walnuts, chopped\n1 1/2 tablespoons cinnamon\n1/4 teaspoon nutmeg\n3/4 cup grated carrots\n3 teaspoons cinnamon\n1/4 teaspoon nutmeg\n3 tablespoons almond butter\n3 tablespoons almond butter\n1/3 cup diced strawberries\n1/3 cup raspberries\n1/3 cup blueberries\nNonstick cooking spray",
    "directions": "Preheat the oven to 375°F (190°C).\nTo make the flax eggs, combine the flax meal and water in a small bowl and mix well. Set aside for 10 minutes to thicken.\nIn a large bowl, combine the oats, quinoa, baking powder, salt, maple syrup, coconut oil, vanilla, flax eggs, and bananas, and mix until well-combined.\nDivide the base dough equally between 4 medium bowls.\nAdd the peanut butter and chocolate chips to a bowl and mix until combined.\nAdd the apple, walnuts, cinnamon, and nutmeg to another bowl and mix until combined.\nAdd the carrots, cinnamon, nutmeg, and almond butter to another bowl and mix until combined.\nAdd the almond butter, strawberries, raspberries, and blueberries to the last bowl and mix until combined.\nGrease 2, 9x13-inch (23x33-cm) baking pans with nonstick spray. Transfer the bar mixtures to the pans, packing each mixture into half of a pan with a spoon or spatula.\nBake for 25-30 minutes, until the edges are slightly golden brown.\nRemove the pans from the oven and let the bars cool for 20 minutes, then refrigerate for at least 30 minutes or up to 5 days. Gently cut each flavor into 6 bars, then remove from the pans with a spatula.\nEnjoy!",
    "tags": "Breakfast",
    "rating": "",
    "publicUrl": "https://www.plantoeat.com/recipes/16687888",
    "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16687888/b16ace53a4f663e77774571db54f16ac701ff494-original.jpg?1535323204",
    "private": "no",
    "nutritionalScoreGeneric": "",
    "calories": "",
    "fat": "",
    "cholesterol": "",
    "sodium": "",
    "sugar": "",
    "carbohydrate": "",
    "fiber": "",
    "protein": "",
    "cost": ""
  },
  {
    "id": 8,
    "title": "Healthy No Bake Peanut Butter Pretzel Granola Bars",
    "course": "Snacks and Sandwiches",
    "cuisine": "American",
    "mainIngredient": "",
    "description": "Healthy No-Bake Peanut Butter Pretzel Bars.",
    "source": "http://peanutbutterpluschocolate.com/healthy-no-bake-peanut-butter_pretzel-granola-bars/",
    "url": "http://peanutbutterpluschocolate.com/healthy-no-bake-peanut-butter_pretzel-granola-bars/",
    "urlHost": "peanutbutterpluschocolate.com",
    "prepTime": 5,
    "cookTime": 0,
    "totalTime": 5,
    "servings": 9,
    "yield": "",
    "ingredients": "1 mashed banana, ripe\n3/4 c peanut butter\n1/4 c agave\n2 1/2 c rolled oats, (gluten-free)\n1/4 c pretzels pieces, (gluten-free)\n1 tbsp chia seeds",
    "directions": "In a large bowl, stir together the banana mash, peanut butter and agave until well combined. Add in the oats and chia seeds and stir well. Fold in the pretzel pieces.\nPress the mixture evenly into the bottom of an 8x8 inch pan lined with parchment paper.\nChill in the freezer for 20 minutes before cutting into 9 squares and serving.",
    "tags": "Dessert, Snack",
    "rating": "",
    "publicUrl": "https://www.plantoeat.com/recipes/16687930",
    "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16687930/cf62d2d92c4accd37c7238f93735181d1dcfbe98-original.jpg?1535323385",
    "private": "no",
    "nutritionalScoreGeneric": "",
    "calories": 240,
    "fat": "13g",
    "cholesterol": "",
    "sodium": "130mg",
    "sugar": "4g",
    "carbohydrate": "26g",
    "fiber": "5g",
    "protein": "9g",
    "cost": ""
  },
  {
    "id": 9,
    "title": "Slow Cooker Teriyaki Chicken + Crock-Pot Giveaway",
    "course": "Main Course",
    "cuisine": "Asian",
    "mainIngredient": "Chicken",
    "description": "This Slow Cooker Teriyaki Chicken recipe is simple to make, full of great flavor, and made with natural sweeteners.",
    "source": "https://www.gimmesomeoven.com/slow-cooker-teriyaki-chicken-teriyaki/",
    "url": "https://www.gimmesomeoven.com/slow-cooker-teriyaki-chicken-teriyaki/",
    "urlHost": "gimmesomeoven.com",
    "prepTime": 10,
    "cookTime": 250,
    "totalTime": 260,
    "servings": 4,
    "yield": "Yield: About 4 cups shredded chicken",
    "ingredients": "2 lbs boneless, skinless chicken breasts\n2 cloves garlic, minced\n1/2 cup chopped white onion\n1/2 cup honey\n1/2 cup soy sauce, (use low-sodium if desired)\n1/4 cup rice wine vinegar\n1 Tbsp. chopped fresh ginger\n1/8 tsp. freshly ground black pepper\n1/4 cup cold water\n3 Tbsp. cornstarch\noptional toppings: sliced scallions and toasted sesame seeds",
    "directions": "Add the chicken breasts to the bottom of your slow cooker in a single layer.\nIn a separate bowl, whisk together the garlic, onion, honey, soy sauce, rice wine vinegar, ginger, and black pepper until combined. Pour the mixture on top of the chicken breasts. Cover slow cooker, and cook on high for 4-5 hours, or until the chicken is cooked through and shreds easily with a fork. Remove the chicken with a slotted spoon to a separate bowl and shred it using two forks. Transfer the remaining teriyaki sauce from the slow cooker to a medium saucepan.\nMeanwhile in a separate bowl, whisk together the cold water and cornstarch until the cornstarch is dissolved and no longer lumpy. Pour the cornstarch slurry into the teriyaki sauce mixture, and whisk to combine. Bring the mixture to a boil over medium-high heat, and let it boil for about 1-2 minutes or until thickened. Remove from heat, and pour the sauce on top of the shredded chicken. Toss to combine.\nServe topped with scallions (green onions) and toasted sesame seeds if desired.",
    "tags": "Crock Pot, Chicken, Slow Cooker",
    "rating": "",
    "publicUrl": "https://www.plantoeat.com/recipes/16689229",
    "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16689229/996f102a3864582b550a11327cc39380b8da75c6-original.jpg?1535328708",
    "private": "no",
    "nutritionalScoreGeneric": "",
    "calories": "",
    "fat": "",
    "cholesterol": "",
    "sodium": "",
    "sugar": "",
    "carbohydrate": "",
    "fiber": "",
    "protein": "",
    "cost": ""
  },
  {
    "id": 10,
    "title": "Fiesta Chicken Crockpot Recipe",
    "course": "Main Course",
    "cuisine": "Mexican",
    "mainIngredient": "Poultry",
    "description": "",
    "source": "http://mylitter.com/fiesta-chicken-crockpot-recipe/",
    "url": "http://mylitter.com/fiesta-chicken-crockpot-recipe/",
    "urlHost": "mylitter.com",
    "prepTime": 0,
    "cookTime": 360,
    "totalTime": 360,
    "servings": 1,
    "yield": "",
    "ingredients": "4 chicken breast, (frozen or raw)\n1 packet Taco Seasoning, (by the salad dressing)\n1 can black beans, (drained and rinsed)\n1 can salsa not drained\n1 can corn not drained",
    "directions": "Looking for a new slow cooker recipe to feed the troops? This Fiesta Chicken Crockpot Recipe is a great one to add to the rotation!\nYou might have seen this recipe around the internet this past week… my Fiesta Chicken crockpot recipe. Those of you who have been reading my site for a while might have recognized my kitchen anyway…\nI make this for dinner often. It is a simple, easy and DELICIOUS chicken crock pot recipe that my kids love. I love it as well for that matter…\nAnyway, I was in a hurry and made it for dinner last week and was out of a few ingredients and made some substitutions. It looked really pretty when I had it all together and so I snapped a picture and figured I would let you guys know what I was having for dinner.\nWell, 26 MILLION people saw my picture last week with over 550,000 shares of my picture & recipe!! (Then of course you have countless people who stole my picture and reposted exactly my word for word comments and directions as their own, and those were shared a crazy number of times…) But in the end, it is a DANG good chicken recipe!\nI was out of the standard Ranch packet you are supposed to dump on the top, but I had this packet of Fiesta Ranch and so I used that… OMGosh! It made it soooooo good!!\nThis recipe is sooooo easy! You can use raw, frozen or unfrozen chicken. You dump it all in the crockpot, sprinkle the dip packet over it all, and then cook it on high for 4 hours or 6 on low. Then shred the chicken with forks and mix it all up. It looks a little sketchy at this point, but don’t worry. Then we make rice, and serve this over the rice using tortillas to scoop it up OR you can just make chicken tacos. So many choices!\nIf it is a little soupy that is ok. Leave the lid off for a little bit and the liquid will disappear. I think it is good with a little sauce though personally.\nInstead of the usual Rotel I used petite diced tomatoes drained, as my little kids don’t like the spice from Rotel.\nThe cream cheese doesn’t need to cook all day with the chicken. In fact, it might curdle if you boil it. I typically toss it in about 40 minutes before we eat, it just needs to get soft enough for you to stir in.\n**If you don’t feel like heading into the store for all your shopping list for this, you might try the Walmart Grocery Pickup if it’s available in your area (there’s coupon codes all the time)\nCook on high in the slow cooker for 4 hours or 6 on low. Shred with forks and eat over rice with tortillas.\nIf using the Instant Pot, use raw chicken. Cover the chicken with the ingredients listed. Press the poultry button then add 5 minutes to cook the chicken for a total of 20 minutes (some prefer 25 minutes).\nThe Instant Pot will release the pressure. Your chicken will be ready to shred and serve!\nThis Hamilton Beach Stay or Go is currently my favorite Crock Pot. I needed to get one with the latch over the top after one too many spills while taking dinner to a party, friends, or church. Plus they are often 50% off or more with free shipping.\nIf you are having a hard time finding the Fiesta Ranch in your grocery store, they are in all of mine by the salad dressing usually on the top shelf, you can order some Fiesta Ranch HERE.\nIf you like Crock Pot recipes as much as I do, I put together a few of my FAVORITE easy Crock Pot recipes in one place. Head on over HERE to check them out!",
    "tags": "Chicken, Slow Cooker",
    "rating": "",
    "publicUrl": "https://www.plantoeat.com/recipes/16689260",
    "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16689260/2b7f200e5109759150fec43af0e225647611ce23-original.jpg?1535328913",
    "private": "no",
    "nutritionalScoreGeneric": "",
    "calories": "",
    "fat": "",
    "cholesterol": "",
    "sodium": "",
    "sugar": "",
    "carbohydrate": "",
    "fiber": "",
    "protein": "",
    "cost": ""
  },
  {
    "id": 11,
    "title": "Orange Chipotle Chicken with Cilantro Rice",
    "course": "Main Course",
    "cuisine": "American",
    "mainIngredient": "Poultry",
    "description": "",
    "source": "https://www.cleaneatingmag.com/recipes/orange-chipotle-chicken-with-cilantro-rice",
    "url": "https://www.cleaneatingmag.com/recipes/orange-chipotle-chicken-with-cilantro-rice",
    "urlHost": "cleaneatingmag.com",
    "prepTime": 10,
    "cookTime": 6,
    "totalTime": 16,
    "servings": 4,
    "yield": 4,
    "ingredients": "1 tsp chile powder\n1/2 tsp ground cumin\n1/2 tsp sea salt, divided\n1 tsp safflower oil\n4 boneless, skinless chicken breasts, (about 1 lb) rinsed and patted dry, pounded 1/2-inch thick\nJuice 1 medium navel orange, (1/3 cup orange juice)\n2 tbsp pure maple syrup\n1 tbsp chopped chipotle chiles in adobo sauce\n1 tsp orange zest\n2 cups cooked brown rice\n1/4 packed cup chopped cilantro leaves",
    "directions": "In a small bowl, combine chile powder, cumin and 1/4 tsp salt. Heat oil in a large nonstick skillet to medium-high. Tilt skillet to coat bottom lightly. Season both sides of chicken with chile-cumin mixture and cook for 3 minutes per side or until no longer pink in center. Remove from skillet and set aside.\nAdd orange juice and maple syrup to juice and bits left in skillet and cook for 1 minute to thicken slightly (until it measures 1/4 cup liquid), stirring constantly. Remove from heat, stir in chipotle chiles in adobo sauce and orange zest. Add chicken back to skillet, return to heat and cook for 1 minute on medium-high, turning constantly.\nIn a medium bowl, combine rice, cilantro and remaining 1/4 tsp salt. Serve chicken over rice and spoon any excess glaze over top chicken pieces.",
    "tags": "Chicken, Budget Friendly",
    "rating": "",
    "publicUrl": "https://www.plantoeat.com/recipes/16727990",
    "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16727990/a03bff7a41182945fde5f0eff18c57db9765dd4b-original.jpg?1535642619",
    "private": "no",
    "nutritionalScoreGeneric": "",
    "calories": 283,
    "fat": "4 g",
    "cholesterol": "32 mg",
    "sodium": "337 mg",
    "sugar": "8 g",
    "carbohydrate": "32 g",
    "fiber": "2 g",
    "protein": "29 g",
    "cost": ""
  },
  {
    "id": 12,
    "title": "One Pot Hamburger Stroganoff",
    "course": "Main Course",
    "cuisine": "",
    "mainIngredient": "",
    "description": "This One Pot Hamburger Stoganoff is a great weeknight meal! It's quick, easy, filled with simple ingredients, and has NO condensed soup.",
    "source": "https://www.countrysidecravings.com/one-pot-hamburger-stroganoff/",
    "url": "https://www.countrysidecravings.com/one-pot-hamburger-stroganoff/",
    "urlHost": "countrysidecravings.com",
    "prepTime": 10,
    "cookTime": 20,
    "totalTime": 30,
    "servings": 5,
    "yield": "4 -5 servings",
    "ingredients": "salt and pepper to taste\n8 ounces (230g) sliced baby portabella mushrooms\n1 small onion, chopped\n2 tablespoons butter\n1 tablespoon olive oil\n1 pound lean ground beef\n3 cloves garlic, minced\n2 tablespoons all purpose flour\n3 cups (710ml) beef broth, ( I like reduced sodium)\n3 cups (150g) uncooked egg noodles\n1 tablespoon Worcestershire sauce\n1 teaspoon beef bullion, (or 1 cube) (I like better than bullion brand)\n1 teaspoon dried parsley\n2/3 cup (150g) sour cream, (or more if you like it creamier)\nsalt and pepper to taste",
    "directions": "In a large skillet over medium heat cook the mushrooms and onion with the butter and olive oil until softened and mushrooms are lightly browned. Add the ground beef and garlic and cook until beef is no longer pink (or until it is mostly cooked, it will continue to cook as it simmers).\nAdd the flour and stir to coat. Add the broth, uncooked noodles, Worcestershire, beef bullion, and parsley. Cover and simmer for 10 minutes or until pasta is tender. Stir occasionally to prevent sticking. Remove from heat and stir in sour cream. Taste for salt and pepper and season accordingly.",
    "tags": "",
    "rating": "",
    "publicUrl": "https://www.plantoeat.com/recipes/16728004",
    "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16728004/6a042ff093d19a5bfbc27a0c9617f94fa2937757-original.jpg?1535642699",
    "private": "no",
    "nutritionalScoreGeneric": "",
    "calories": "",
    "fat": "",
    "cholesterol": "",
    "sodium": "",
    "sugar": "",
    "carbohydrate": "",
    "fiber": "",
    "protein": "",
    "cost": ""
  },
  {
    "id": 13,
    "title": "Spicy Chicken Breasts",
    "course": "Main Course",
    "cuisine": "",
    "mainIngredient": "",
    "description": "",
    "source": "http://www.centercutcook.com/spicy-chicken-breasts/",
    "url": "http://www.centercutcook.com/spicy-chicken-breasts/",
    "urlHost": "centercutcook.com",
    "prepTime": 5,
    "cookTime": 10,
    "totalTime": 15,
    "servings": 2,
    "yield": "",
    "ingredients": "1 tablespoon Oil\n2 Chicken Breasts, (each breast was approx. half a pound in weight)\n1 tablespoon Sriracha\n3 Garlic cloves, minced\nSalt and Pepper to taste\nChopped Vegetables, (Optional)",
    "directions": "Mix together sriracha, garlic, salt and pepper in a bowl and rub all over the chicken breasts. Set aside for ten to fifteen minutes.\nHeat oil in a skillet and add the chicken breasts. Cook on medium high heat on each side for 3-4 minutes. Switch off the flame, cover and let the chicken rest for 5 more minutes before serving.",
    "tags": "",
    "rating": "",
    "publicUrl": "https://www.plantoeat.com/recipes/16728022",
    "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16728022/5787b645a80520dcb41951611b164ccc92a6067e-original.jpg?1535642799",
    "private": "no",
    "nutritionalScoreGeneric": "",
    "calories": "",
    "fat": "",
    "cholesterol": "",
    "sodium": "",
    "sugar": "",
    "carbohydrate": "",
    "fiber": "",
    "protein": "",
    "cost": ""
  },
  {
    "id": 14,
    "title": "10 Minute Cashew Shrimp",
    "course": "Main Course",
    "cuisine": "Asian",
    "mainIngredient": "Fish",
    "description": "Sweet, crunchy shrimp are stir-fried with crunchy, sweet cashew nuts in this classic Chinese dish that's perfect for week night dinners.",
    "source": "https://www.errenskitchen.com/10-minute-cashew-shrimp/",
    "url": "https://www.errenskitchen.com/10-minute-cashew-shrimp/",
    "urlHost": "errenskitchen.com",
    "prepTime": 5,
    "cookTime": 5,
    "totalTime": 10,
    "servings": 4,
    "yield": "4 servings",
    "ingredients": "1/4 cup Low Sodium Soy Sauce, ( or regular soy sauce)\n1 Tablespoon Rice Wine Vinegar\n1 Tablespoon Packed Brown Sugar\n2 Tablespoons Oyster Sauce\n1/2 teaspoon Toasted Sesame Oil\n3 Tablespoons Vegetable Oil\n1 pound shrimp, (cleaned and seasoned with a little salt & pepper)\n3 cloves garlic, (chopped)\nGround white pepper to taste, (you can use black if need be)\n1 inch piece fresh ginger, (peeled & grated)\n1/4 cup Sherry\n2 Tablespoons Cornstarch, (mixed well with ¼ cup of cold water until smooth)\n1 cup Cashews, (Unsalted )\n2 Green Onions, (Sliced)\nCooked Rice for Serving",
    "directions": "In a small bowl, mix together the soy sauce, rice wine vinegar, brown sugar, oyster sauce, and sesame oil. Set aside.\nHeat the vegetable oil in a wok or large skillet over high heat and add the shrimp and stir fry until pink (about 2 minutes). Remove from wok and set aside.\nUsing the same pan, add in the garlic and ginger and stir to combine. Cook for about a minute.\nPour in the sherry. Stir it around, scraping the bottom of the pan to loosen all the flavorful bits that may have stuck to the wok. Cook for about 2 minutes to cook off the alcohol.\nTurn the heat to medium-low and pour in the sauce mixture, then mix in the cornstarch mixture. Stir the sauce for 1 to 2 minutes to thicken, then add the cashews and stir to coat everything with the sauce. You can add a little water if the sauce looks too thick. Add the shrimp to the sauce.\nSprinkle on the green onions. Serve with cooked rice.",
    "tags": "Easy, Quick",
    "rating": "",
    "publicUrl": "https://www.plantoeat.com/recipes/16728055",
    "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16728055/950c003fa1f523ac1b2e0dcea2aa0c74d5176fe2-original.jpg?1535642937",
    "private": "no",
    "nutritionalScoreGeneric": "",
    "calories": 311,
    "fat": "16 g",
    "cholesterol": "285 mg",
    "sodium": "1662 mg",
    "sugar": "3 g",
    "carbohydrate": "12 g",
    "fiber": "",
    "protein": "25 g",
    "cost": ""
  },
  {
    "id": 15,
    "title": "Honey Dijon Garlic Chicken Breasts",
    "course": "Main Course",
    "cuisine": "",
    "mainIngredient": "",
    "description": "Boneless skinless chicken Breasts quickly baked in an intensely flavoured honey, garlic and Dijon mustard glaze.",
    "source": "http://www.rockrecipes.com/honey-dijon-garlic-chicken-breasts",
    "url": "http://www.rockrecipes.com/honey-dijon-garlic-chicken-breasts",
    "urlHost": "rockrecipes.com",
    "prepTime": 10,
    "cookTime": 30,
    "totalTime": 40,
    "servings": 4,
    "yield": 4,
    "ingredients": "4 large boneless skinless chicken breasts, (about 6 ounces each)\n3 tbsp butter\n6 cloves minced garlic\npinch salt and pepper\n1/3 cup honey\n2 tbsp whole grain Dijon mustard",
    "directions": "Line an 8x8 inch baking pan with aluminum foil. Use a baking pan that is large enough to have a half inch of space around each chicken breast but no more. Using too large a baking dish can cause the glaze to be too shallow in the pan and burn easily. Place the empty pan in a 425 degree oven to heat up while you prepare the glaze.\n, To prepare the glaze\nMelt the butter in a small saute pan. Add the garlic and cook for only 30-60 seconds to soften it. Do not brown the garlic.\nAdd the honey, Dijon mustard and a pinch of salt and pepper. Stir well to blend and simmer over medium heat for one or two minutes begin to reduce the glaze.\nLightly season the chicken breasts with salt and pepper. Remove the hot pan from the oven and place the chicken breasts an equal distance apart in the pan. Pour the hot glaze evenly over the chicken.\nReturn the pan to the 425 degree F oven and bake for 15 minutes. Remove from oven and baste the breasts with the glaze in the bottom of the pan. return to the oven for an additional 15-20 minutes or until a neat thermometer inserted into the center of the thickest part of the breast reads 170 degrees F.\nAllow the chicken to rest for 5 minutes before serving.",
    "tags": "",
    "rating": "",
    "publicUrl": "https://www.plantoeat.com/recipes/16741465",
    "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16741465/cb14c2a77dbf7875b41d1f84fc73974ffa0b5c4f-original.jpg?1535738019",
    "private": "no",
    "nutritionalScoreGeneric": "",
    "calories": 302,
    "fat": "11 g",
    "cholesterol": "95 mg",
    "sodium": "294 mg",
    "sugar": "23 g",
    "carbohydrate": "25 g",
    "fiber": "",
    "protein": "24 g",
    "cost": ""
  },
  {
    "id": 16,
    "title": "Orange Tofu",
    "course": "Main Course",
    "cuisine": "",
    "mainIngredient": "",
    "description": "Orange Tofu is a delicious and easy tofu recipe that your entire family will love! The crispy tofu bites are flavored with an orange sauce and served over rice.",
    "source": "https://vegetarianmamma.com/orange-tofu/",
    "url": "https://vegetarianmamma.com/orange-tofu/",
    "urlHost": "vegetarianmamma.com",
    "prepTime": 15,
    "cookTime": 10,
    "totalTime": 25,
    "servings": 4,
    "yield": "4 people",
    "ingredients": "1 c fresh orange juice\n1 T orange zest\n5 T coconut aminos\n1 T fresh ginger, (grated or diced)\n1 block extra firm tofu\n2-3 T oil\n1 c red bell pepper, (deseeded and diced)\n2 T cornstarch\n2 c cooked rice\nsesame seeds, or green onions for garnish",
    "directions": "Start by pressing your tofu for at least 10 minutes using the EZ Tofu Press.\nThen dice your tofu into bite sized pieces and set aside.\nCombine fresh orange juice, orange zest, coconut aminos and ginger. Stir to combine.\nPut tofu bites and orange juice mixture into a bag. Marinate for 30 minutes.\nHeat 1-2 T of oil in a pan over medium heat. Remove tofu from marinade. Fry tofu for 2 minutes, add in diced bell pepper. Saute until tofu is golden brown.\nMeanwhile, bring the marinade to a boil and add in cornstarch. Stir to thicken. Once liquid begins to thicken remove from heat.\nAdd orange sauce to the tofu pan. Stir to coat.\nDivide rice among 4 plates. Top with orange tofu and bell peppers. Garnish with green onions or sesame seeds.\nENJOY!",
    "tags": "",
    "rating": "",
    "publicUrl": "https://www.plantoeat.com/recipes/16741488",
    "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16741488/63b76e69f620abb981885c0ee51990451ddca821-original.jpg?1535738100",
    "private": "no",
    "nutritionalScoreGeneric": "",
    "calories": "",
    "fat": "",
    "cholesterol": "",
    "sodium": "",
    "sugar": "",
    "carbohydrate": "",
    "fiber": "",
    "protein": "",
    "cost": ""
  },
  {
    "id": 17,
    "title": "Caramelized Tofu Recipe",
    "course": "Main Course",
    "cuisine": "",
    "mainIngredient": "",
    "description": "Serves 2 - 3 as a main, 4 as a side",
    "source": "https://www.101cookbooks.com/archives/caramelized-tofu-recipe.html",
    "url": "https://www.101cookbooks.com/archives/caramelized-tofu-recipe.html",
    "urlHost": "101cookbooks.com",
    "prepTime": 0,
    "cookTime": 10,
    "totalTime": 10,
    "servings": 1,
    "yield": "",
    "ingredients": "7-8 ounces extra-firm tofu cut into thin 1-inch segments, (see photo)\nfine-grain sea salt, a couple pinches of\nolive, a couple splashes of - or peanut oil\n2 medium cloves garlic, minced\n1/3 cup pecans, toasted and chopped\n3 tablespoons fine-grain natural cane sugar, or brown sugar\n1/4 cup cilantro, chopped\n1/2 lb. brussels sprouts, washed and cut into 1/8-inch wide ribbons",
    "directions": "I used the Wildwood Organics baked savory tofu here, it browned up nicely and held it's shape, and as was mentoned in the comments it is non-GMO. Though any extra-firm tofu will work.\nCook the tofu strips in large hot skillet (or pot) with a bit of salt and a splash of oil. Saute until slightly golden, about 4 minutes. Add the garlic and pecans, and cook for another minute. Stir in sugar. Cook for another couple of minutes. Remove from heat and stir in cilantro. Scrape the tofu out onto a plate and set aside while you cook the brussels sprouts.\nIn the same pan (no need to wash), add a touch more oil, another pinch of salt, and dial the heat up to medium-high. When the pan is nice and hot stir in the shredded brussels sprouts. Cook for 2 - 3 minutes, stirring a couple times (but not too often) until you get some golden bits, and the rest of the sprouts are bright and delicious.",
    "tags": "",
    "rating": "",
    "publicUrl": "https://www.plantoeat.com/recipes/16741504",
    "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16741504/91d64fad6d7a58e44ded7e732ca50b2d2d446c9c-original.jpg?1535738147",
    "private": "no",
    "nutritionalScoreGeneric": "",
    "calories": "",
    "fat": "",
    "cholesterol": "",
    "sodium": "",
    "sugar": "",
    "carbohydrate": "",
    "fiber": "",
    "protein": "",
    "cost": ""
  },
  {
    "id": 18,
    "title": "Butter Garlic Herb Steak Foil Packets",
    "course": "Main Course",
    "cuisine": "",
    "mainIngredient": "",
    "description": "Butter Garlic Herb Steak Foil Packets have melt in your mouth beef with hearty veggies that are grilled to perfection with butter that has garlic and herbs inside. This is one amazing meal that you don't want to miss out on!",
    "source": "https://therecipecritic.com/butter-garlic-herb-steak-foil-packets/",
    "url": "https://therecipecritic.com/butter-garlic-herb-steak-foil-packets/",
    "urlHost": "therecipecritic.com",
    "prepTime": 15,
    "cookTime": 15,
    "totalTime": 30,
    "servings": 4,
    "yield": 4,
    "ingredients": "1 pound small red potatoes, cut into fourths\n2 carrots, sliced\n1 red bell pepper, cubed\n1 green bell pepper, cubed\n1/2 red onion, cut into cubes\nsalt and pepper\n1 Tablespoon olive oil\n1 1/2 pound top sirloin steak, cut into one inch cubes*\n, Garlic Herb Butter:\n1/2 cup butter, room temperature\n1/4 cup freshly chopped parsley\n4 garlic cloves, minced\n1 teaspoon fresh rosemary, chopped\n1 teaspoon fresh thyme, chopped\n1/2 teaspoon salt\n1/4 teaspoon pepper",
    "directions": "In a medium sized bowl add the red potatoes, carrots, bell peppers, and red onion. Add salt and pepper and toss with olive oil.\nPlace four 18x12-inch pieces of heavy aluminum foil on counter. Evenly place vegetable mixture on each piece of foil. Top vegetables with steak.\nTo make the garlic herb butter: In a small bowl add the butter, parsley, garlic, rosemary, thyme, salt and pepper. Divide evenly and place on top of the steak. Double fold top and ends of each piece of foil, leaving space for steam to gather.\nPlace packets on the grill and coverl. Grill 15 minutes or until steak is cooked through and veggies are tender. Carefully open packets and serve.",
    "tags": "",
    "rating": "",
    "publicUrl": "https://www.plantoeat.com/recipes/16741523",
    "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16741523/4f4dbccde8cf19d836bedd1db7d6459fa1c9610f-original.jpg?1535738233",
    "private": "no",
    "nutritionalScoreGeneric": "",
    "calories": "",
    "fat": "",
    "cholesterol": "",
    "sodium": "",
    "sugar": "",
    "carbohydrate": "",
    "fiber": "",
    "protein": "",
    "cost": ""
  },
  {
    "id": 19,
    "title": "Chicken Parmesan Foil Packets",
    "course": "Main Course",
    "cuisine": "",
    "mainIngredient": "",
    "description": "Parmesan Chicken Foil Packets contain a complete dinner in one tidy little packet! Fresh summer zucchini, zesty tomato sauce and tender chicken breasts are grilled until perfectly cooked and topped with melty mozzarella cheese. This is going to become your favorite summer meal!",
    "source": "https://www.spendwithpennies.com/parmesan-chicken-foil-packets/",
    "url": "https://www.spendwithpennies.com/parmesan-chicken-foil-packets/",
    "urlHost": "spendwithpennies.com",
    "prepTime": 15,
    "cookTime": 20,
    "totalTime": 35,
    "servings": 4,
    "yield": "4 servings",
    "ingredients": "4 chicken breasts, (boneless, skinless)\n3 cups pasta sauce\n2 zucchini, (sliced)\n1/2 cup parmesan cheese, (shredded)\n1 cup mozzarella cheese, (shredded)\n1 teaspoon garlic powder\n1 teaspoon Italian seasoning, (sprinkle)\nsalt & pepper, (to taste)\n1/4 cup olive oil\nspaghetti, (cooked)\nparsley, (freshly chopped)",
    "directions": "Preheat grill to medium heat. Spray four 12x18 inch foil pieces with cooking spray.\nDivide zucchini over the four pieces of foil. Sprinkle with salt, pepper and italian seasoning to taste and 2T parmesan cheese.\nAdd 1/3 cup pasta sauce on top of the zucchini. Place a chicken breast on top of the sauce.\nDrizzle each chicken breast with olive oil then sprinkle with garlic powder, italian seasoning, salt and pepper.\nSeal each packet. Place on heated grill with the chicken side down. Grill for 8 minutes.\nFlip each packet and continue to grill for another 8-10 minutes or until juice run clear and chicken reaches 165 degrees.\nOpen each packet by slicing with a knife. Sprinkle 1/4 cup mozzarella cheese on each chicken breast and heat to melt. (see note)\nIf desired, cook pasta according to package directions and heat remaining sauce.\nRemove the chicken and zucchini from each packet and place on top of the pasta. Pour any extra sauce from the packet on top as well.\nSprinkle with freshly grated parmesan and garnish with fresh parsley.",
    "tags": "",
    "rating": "",
    "publicUrl": "https://www.plantoeat.com/recipes/16741530",
    "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16741530/65401f6583473d28beed9b6c4bc62cb559c642d9-original.jpg?1535738244",
    "private": "no",
    "nutritionalScoreGeneric": "",
    "calories": 530,
    "fat": "23 g",
    "cholesterol": "158 mg",
    "sodium": "1643 mg",
    "sugar": "10 g",
    "carbohydrate": "15 g",
    "fiber": "4 g",
    "protein": "65 g",
    "cost": ""
  },
  {
    "id": 20,
    "title": "Bacon Ranch Chicken Foil Packets",
    "course": "Main Course",
    "cuisine": "",
    "mainIngredient": "",
    "description": "These bacon ranch chicken foil packets are a super easy dinner option with minimal cleanup! Chicken breasts are cooked with potatoes and ranch flavored butter, then topped with melted cheese and bacon for a meal that's sure to please any crowd.",
    "source": "https://www.dinneratthezoo.com/bacon-ranch-chicken-foil-packets/",
    "url": "https://www.dinneratthezoo.com/bacon-ranch-chicken-foil-packets/",
    "urlHost": "dinneratthezoo.com",
    "prepTime": 15,
    "cookTime": 45,
    "totalTime": 60,
    "servings": 4,
    "yield": 4,
    "ingredients": "6 tablespoons butter, (melted)\n2 tablespoons ranch seasoning powder\nsalt and pepper to taste\n4 medium sized chicken breasts, (approximately 4 ounces each)\n1 pound small red potatoes, (halved or quartered)\nnonstick cooking spray\n1 cup shredded cheddar cheese\n4 slices bacon, (cooked and crumbled)\n2 tablespoons chopped parsley",
    "directions": "Preheat the oven to 425 degrees or a grill over medium high heat. In a small bowl whisk together the butter, ranch seasoning, and salt and pepper to taste.\nCoat 4 large squares of foil with cooking spray.\nPlace the potatoes in a bowl and drizzle with 4 tablespoons of the ranch butter over the top. Toss to coat evenly.\nPlace a chicken breast onto each of the foil squares and season with salt and pepper to taste. Divide the potatoes evenly among the 4 foil squares and arrange them around the chicken.\nDrizzle the remaining 2 tablespoons of butter over the chicken breasts. Fold the edges of the foil over the chicken and potatoes to make a packet.\nBake for 45 minutes or grill for 30 minutes. Open the packets and sprinkle the cheese over the chicken and potatoes. Leave the packets open and return to the oven or grill for 2-3 minutes or until cheese melts. Sprinkle with bacon and parsley and serve.",
    "tags": "",
    "rating": "",
    "publicUrl": "https://www.plantoeat.com/recipes/16741543",
    "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16741543/2723c77dddd87110bf898093050f741a8c9c167e-original.jpg?1535738282",
    "private": "no",
    "nutritionalScoreGeneric": "",
    "calories": 510,
    "fat": "28 g",
    "cholesterol": "161 mg",
    "sodium": "785 mg",
    "sugar": "1 g",
    "carbohydrate": "22 g",
    "fiber": "1 g",
    "protein": "36 g",
    "cost": ""
  }]


export default menu;